POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "relokasipelem",
  "password": "relokasaipelem"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "relokasipelem",
  "password": "relokasaipelem"
}